[theme]
name = "slick"
[theme.overrides]
idle_bg = "#123456"
idle_fg = "#abcdef"

[icons]
name = "awesome"

[[block]]
block = "disk_space"
path = "/"
alias = "ROOT"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "disk_space"
path = "/home"
alias = "HOME"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "net"
device = "wlo1"
ssid = true
ip = false
speed_up = false
graph_up = false
interval = 5

[[block]]
block = "xrandr"
icons = true
resolution = true
interval = 2

[[block]]
block = "toggle"

text = "DEFAULT"
command_state = "xrandr | egrep 'eDP1.+primary'"
command_on = "~/.screenlayout/default.sh"
command_off = "~/.screenlayout/dual-screen.sh"
interval = 5
